spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eshop-hexa
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  messages:
    basename: messages, errors
    encoding: ISO-8859-1
  kafka:
    bootstrap-servers: localhost:9093
  batch:
    jdbc:
      initialize-schema: always
token:
  signing:
    key: privateKeyprivateKeyprivateKeyprivateKeyprivateKeyprivateKeyprivateKey
eshop.kafka:
  producers:
    - name: category
      enabled: true
      topic: categoryTopic
    - name: producer2
      enabled: false

batch:
  input-file: category-list.csv
