spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eshop-hexa
    username: root3
    password: root
  jpa:
    hibernate:
      ddl-auto: update

token:
  signing:
    key: privateKeyprivateKeyprivateKeyprivateKeyprivateKeyprivateKeyprivateKey