spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eshop-hexa
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  messages:
    basename: messages, errors
    encoding: ISO-8859-1
token:
  signing:
    key: privateKeyprivateKeyprivateKeyprivateKeyprivateKeyprivateKeyprivateKey


